name: Check Resources

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  validate:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Run Checks
        run: |
          gem install awesome_bot
          gem install danger
          awesome_bot -f README.md --allow-ssl --allow 302,429
          danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
